server:
  port: 8087

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb?stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  cloud:
    config:
      enabled: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: redis-password
      timeout: 2000
      database: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    enabled: true
  api-docs:
    path: /api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true