server:
  port: 8083

spring:
  application:
    name: lecture-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb?stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: redis-password
      timeout: 2000
      database: 0

  graphql:
    graphiql:
      enabled: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true