# Server Configuration
server:
  port: 8083

# Spring Boot Application Configuration
spring:
  application:
    name: lecture-service-reactive

  # --- R2DBC Configuration ---
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydb
    username: postgres
    password: postgres

  # --- Redis Configuration (Reactive) ---
  # cache:
  #   type: redis # Enables Redis as the cache manager
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379
  #     password: redis-password # Set your Redis password here if required
  #     timeout: 2000 # Connection timeout in milliseconds
  #     database: 0 # Redis database index

  # --- GraphQL Configuration ---
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    websocket:
      path: /lectures/graphql
    path: /lectures/graphql

# Eureka Client Configuration (Service Discovery)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

